require('dotenv').config({ path: '.env.local' });
const { createClient } = require('@sanity/client');

const client = createClient({
  projectId: '7kf72dsd',
  dataset: 'production',
  apiVersion: '2024-01-01',
  token: process.env.SANITY_API_WRITE_TOKEN,
  useCdn: false,
});

const pages = [
  {
    _type: 'page',
    _id: 'page-tentang-kami',
    title: 'Tentang Kami',
    slug: { _type: 'slug', current: 'tentang-kami' },
    description: 'Mengenal lebih dekat Warta Nusantara — portal berita Indonesia terkini, terpercaya, dan informatif.',
    body: [
      { _type: 'block', _key: 'intro1', style: 'normal', children: [{ _type: 'span', _key: 's1', text: 'Warta Nusantara', marks: ['strong'] }, { _type: 'span', _key: 's2', text: ' adalah portal berita digital Indonesia yang menyajikan informasi terkini, terverifikasi, dan komprehensif bagi masyarakat Indonesia. Beroperasi melalui ', }, { _type: 'span', _key: 's3', text: 'tanahjarang.com', marks: ['strong'] }, { _type: 'span', _key: 's4', text: ', kami hadir sebagai sumber informasi yang dapat diandalkan untuk berbagai kalangan — mulai dari pembaca umum, pelaku bisnis, hingga akademisi.' }] },
      { _type: 'block', _key: 'intro2', style: 'normal', children: [{ _type: 'span', _key: 's5', text: 'Dengan jangkauan yang meliputi berita nasional, internasional, ekonomi, teknologi, olahraga, hiburan, hingga komoditas dan mineral, Warta Nusantara berkomitmen menjadi jendela informasi yang menghubungkan masyarakat Indonesia dengan perkembangan terkini di dalam dan luar negeri.' }] },
      { _type: 'block', _key: 'visi-h', style: 'h2', children: [{ _type: 'span', _key: 's6', text: 'Visi' }] },
      { _type: 'block', _key: 'visi', style: 'normal', children: [{ _type: 'span', _key: 's7', text: 'Menjadi portal berita digital terdepan dan terpercaya di Indonesia yang memberikan dampak positif bagi perkembangan informasi publik, dengan mengedepankan akurasi, integritas, dan inovasi dalam setiap liputan.' }] },
      { _type: 'block', _key: 'misi-h', style: 'h2', children: [{ _type: 'span', _key: 's8', text: 'Misi' }] },
      { _type: 'block', _key: 'misi1', style: 'normal', list: 'number', level: 1, children: [{ _type: 'span', _key: 's9', text: 'Menyajikan Berita Akurat dan Terverifikasi', marks: ['strong'] }, { _type: 'span', _key: 's10', text: ' — Setiap informasi yang kami publikasikan melalui proses verifikasi ketat dari sumber-sumber yang kredibel dan dapat dipertanggungjawabkan.' }] },
      { _type: 'block', _key: 'misi2', style: 'normal', list: 'number', level: 1, children: [{ _type: 'span', _key: 's11', text: 'Menjaga Netralitas dan Objektivitas', marks: ['strong'] }, { _type: 'span', _key: 's12', text: ' — Kami berkomitmen menyajikan berita secara berimbang, memaparkan berbagai sudut pandang tanpa memihak pada kepentingan tertentu.' }] },
      { _type: 'block', _key: 'misi3', style: 'normal', list: 'number', level: 1, children: [{ _type: 'span', _key: 's13', text: 'Memberikan Akses Informasi yang Inklusif', marks: ['strong'] }, { _type: 'span', _key: 's14', text: ' — Informasi berkualitas harus dapat diakses oleh semua lapisan masyarakat tanpa memandang latar belakang.' }] },
      { _type: 'block', _key: 'misi4', style: 'normal', list: 'number', level: 1, children: [{ _type: 'span', _key: 's15', text: 'Menggunakan Teknologi Secara Bertanggung Jawab', marks: ['strong'] }, { _type: 'span', _key: 's16', text: ' — Kami memanfaatkan teknologi modern untuk meningkatkan kualitas liputan, sambil tetap menjaga standar etika jurnalistik yang ketat.' }] },
      { _type: 'block', _key: 'misi5', style: 'normal', list: 'number', level: 1, children: [{ _type: 'span', _key: 's17', text: 'Mendukung Kemerdekaan Pers', marks: ['strong'] }, { _type: 'span', _key: 's18', text: ' — Kami menjalankan fungsi jurnalistik secara independen, terbebas dari intervensi politik, ekonomi, maupun kekuatan lain yang dapat mengorbankan kebenaran.' }] },
      { _type: 'block', _key: 'standar-h', style: 'h2', children: [{ _type: 'span', _key: 's19', text: 'Standar Editorial' }] },
      { _type: 'block', _key: 'standar-p', style: 'normal', children: [{ _type: 'span', _key: 's20', text: 'Warta Nusantara menerapkan standar editorial yang ketat sesuai Pedoman Umum Pemberitaan Dewan Pers dan Kode Etik Jurnalistik Indonesia.' }] },
      { _type: 'block', _key: 'standar-h3', style: 'h3', children: [{ _type: 'span', _key: 's21', text: 'Prinsip Jurnalistik' }] },
      { _type: 'block', _key: 'bullet1', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's22', text: 'Verifikasi Fakta', marks: ['strong'] }, { _type: 'span', _key: 's23', text: ' — Setiap berita harus melalui minimal dua sumber independen sebelum dipublikasikan.' }] },
      { _type: 'block', _key: 'bullet2', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's24', text: 'Transparansi Sumber', marks: ['strong'] }, { _type: 'span', _key: 's25', text: ' — Kami selalu menyertakan sumber informasi dan memberikan atribusi yang jelas kepada narasumber.' }] },
      { _type: 'block', _key: 'bullet3', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's26', text: 'Pemisahan Fakta dan Opini', marks: ['strong'] }, { _type: 'span', _key: 's27', text: ' — Berita dan opini kami sajikan dalam rubrik terpisah dengan label yang jelas.' }] },
      { _type: 'block', _key: 'bullet4', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's28', text: 'Hak Jawab dan Koreksi', marks: ['strong'] }, { _type: 'span', _key: 's29', text: ' — Kami memberikan ruang bagi pihak yang merasa dirugikan untuk memberikan jawaban.' }] },
      { _type: 'block', _key: 'bullet5', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's30', text: 'Perlindungan Narasumber', marks: ['strong'] }, { _type: 'span', _key: 's31', text: ' — Identitas narasumber yang meminta perlindungan akan kami jaga kerahasiaannya.' }] },
      { _type: 'block', _key: 'tim-h', style: 'h2', children: [{ _type: 'span', _key: 's32', text: 'Tim Redaksi' }] },
      { _type: 'block', _key: 'tim-p', style: 'normal', children: [{ _type: 'span', _key: 's33', text: 'Warta Nusantara dikelola oleh tim redaksi profesional dengan pengalaman bertahun-tahun di bidang jurnalistik digital. Setiap anggota tim telah melalui pelatihan dan sertifikasi di bidang kejurnalistikan, memastikan setiap konten yang kami hasilkan memenuhi standar profesionalisme tertinggi.' }] },
      { _type: 'block', _key: 'tim-p2', style: 'normal', children: [{ _type: 'span', _key: 's34', text: 'Proses editorial kami meliputi tahapan penulisan, editing, fact-checking, dan final review sebelum sebuah artikel layak dipublikasikan.' }] },
      { _type: 'block', _key: 'kategori-h', style: 'h2', children: [{ _type: 'span', _key: 's35', text: 'Kategori Liputan' }] },
      { _type: 'block', _key: 'kat1', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's36', text: 'Berita Nasional', marks: ['strong'] }, { _type: 'span', _key: 's37', text: ' — Perkembangan politik, hukum, sosial, dan kebijakan publik di Indonesia' }] },
      { _type: 'block', _key: 'kat2', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's38', text: 'Berita Internasional', marks: ['strong'] }, { _type: 'span', _key: 's39', text: ' — Peristiwa global yang berdampak pada Indonesia dan kawasan Asia Tenggara' }] },
      { _type: 'block', _key: 'kat3', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's40', text: 'Ekonomi dan Bisnis', marks: ['strong'] }, { _type: 'span', _key: 's41', text: ' — Analisis pasar, kebijakan ekonomi, dan perkembangan dunia usaha' }] },
      { _type: 'block', _key: 'kat4', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's42', text: 'Teknologi', marks: ['strong'] }, { _type: 'span', _key: 's43', text: ' — Inovasi digital, perkembangan startup, dan tren teknologi terkini' }] },
      { _type: 'block', _key: 'kat5', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's44', text: 'Olahraga', marks: ['strong'] }, { _type: 'span', _key: 's45', text: ' — Liputan komprehensif dari dunia sepak bola, bulu tangkis, dan olahraga lainnya' }] },
      { _type: 'block', _key: 'kat6', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's46', text: 'Hiburan dan Gaya Hidup', marks: ['strong'] }, { _type: 'span', _key: 's47', text: ' — Berita hiburan, review, dan tren gaya hidup masa kini' }] },
      { _type: 'block', _key: 'kat7', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's48', text: 'Komoditas dan Mineral', marks: ['strong'] }, { _type: 'span', _key: 's49', text: ' — Harga komoditas, perkembangan pertambangan, dan analisis pasar komoditas Indonesia' }] },
      { _type: 'block', _key: 'komitmen-h', style: 'h2', children: [{ _type: 'span', _key: 's50', text: 'Komitmen terhadap Kualitas' }] },
      { _type: 'block', _key: 'komitmen-p', style: 'normal', children: [{ _type: 'span', _key: 's51', text: 'Kami memahami bahwa kepercayaan pembaca adalah aset paling berharga. Oleh karena itu, kami terus berupaya meningkatkan kualitas layanan melalui:' }] },
      { _type: 'block', _key: 'komitmen1', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's52', text: 'Pembaruan berita secara real-time untuk peristiwa terkini' }] },
      { _type: 'block', _key: 'komitmen2', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's53', text: 'Analisis mendalam untuk membantu pembaca memahami konteks sebuah peristiwa' }] },
      { _type: 'block', _key: 'komitmen3', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's54', text: 'Desain antarmuka yang intuitif dan ramah pengguna di berbagai perangkat' }] },
      { _type: 'block', _key: 'komitmen4', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's55', text: 'Optimasi kecepatan akses untuk pengalaman membaca yang optimal' }] },
      { _type: 'block', _key: 'komitmen5', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's56', text: 'Fitur interaktif seperti komentar dan reaksi untuk membangun komunitas pembaca yang aktif' }] },
      { _type: 'block', _key: 'ai-h', style: 'h2', children: [{ _type: 'span', _key: 's57', text: 'Penggunaan Teknologi AI' }] },
      { _type: 'block', _key: 'ai-p', style: 'normal', children: [{ _type: 'span', _key: 's58', text: 'Warta Nusantara mengakui pentingnya transparansi dalam penggunaan teknologi. Kami menggunakan kecerdasan buatan (AI) sebagai alat bantu dalam beberapa aspek produksi konten, seperti pengumpulan data dan penyusunan draf awal. Namun, setiap konten yang dihasilkan dengan bantuan AI selalu melalui proses review dan editing oleh editor manusia sebelum dipublikasikan.' }] },
      { _type: 'block', _key: 'kontak-h', style: 'h2', children: [{ _type: 'span', _key: 's59', text: 'Hubungi Kami' }] },
      { _type: 'block', _key: 'kontak-p', style: 'normal', children: [{ _type: 'span', _key: 's60', text: 'Kami terbuka untuk masukan, kritik, dan kerja sama.' }] },
      { _type: 'block', _key: 'kontak1', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's61', text: 'Email: ' }, { _type: 'span', _key: 's62', text: 'info@tanahjarang.com', marks: ['underline'] }] },
      { _type: 'block', _key: 'kontak2', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's63', text: 'Halaman: Hubungi Kami' }] },
      { _type: 'block', _key: 'kontak-p2', style: 'normal', children: [{ _type: 'span', _key: 's64', text: 'Untuk kerja sama bisnis dan periklanan, silakan hubungi kami melalui email di atas dengan subjek "Kerja Sama Bisnis".' }] },
    ],
  },
  {
    _type: 'page',
    _id: 'page-editorial-policy',
    title: 'Kebijakan Editorial',
    slug: { _type: 'slug', current: 'editorial-policy' },
    description: 'Kebijakan editorial Warta Nusantara — standar penulisan, verifikasi fakta, dan etika jurnalistik yang kami junjung.',
    body: [
      { _type: 'block', _key: 'ep1', style: 'normal', children: [{ _type: 'span', _key: 's1', text: 'Kebijakan editorial ini menjelaskan standar, prosedur, dan prinsip yang mendasari setiap konten yang dipublikasikan di Warta Nusantara. Kebijakan ini selaras dengan Pedoman Umum Pemberitaan Dewan Pers dan Kode Etik Jurnalistik Indonesia.' }] },
      { _type: 'block', _key: 'ep-h2-1', style: 'h2', children: [{ _type: 'span', _key: 's2', text: 'Standar Penulisan' }] },
      { _type: 'block', _key: 'ep-p2', style: 'normal', children: [{ _type: 'span', _key: 's3', text: 'Semua konten di Warta Nusantara ditulis berdasarkan standar jurnalistik Indonesia yang berlaku. Penulis wajib mematuhi ketentuan berikut:' }] },
      { _type: 'block', _key: 'ep-b1', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's4', text: 'Memverifikasi fakta dari minimal 2 sumber berbeda sebelum dipublikasikan' }] },
      { _type: 'block', _key: 'ep-b2', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's5', text: 'Memberikan hak jawab bagi pihak yang disebutkan dalam berita' }] },
      { _type: 'block', _key: 'ep-b3', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's6', text: 'Membedakan antara berita (fakta) dan opini secara jelas' }] },
      { _type: 'block', _key: 'ep-b4', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's7', text: 'Menyertakan sumber dan referensi untuk setiap klaim yang disampaikan' }] },
      { _type: 'block', _key: 'ep-b5', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's8', text: 'Menggunakan bahasa Indonesia yang baku, jelas, dan mudah dipahami' }] },
      { _type: 'block', _key: 'ep-h2-2', style: 'h2', children: [{ _type: 'span', _key: 's9', text: 'Verifikasi Fakta' }] },
      { _type: 'block', _key: 'ep-p3', style: 'normal', children: [{ _type: 'span', _key: 's10', text: 'Sebelum artikel dipublikasikan, dilakukan proses verifikasi fakta oleh tim editor yang terpisah dari penulis. Proses verifikasi meliputi:' }] },
      { _type: 'block', _key: 'ep-b6', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's11', text: 'Keakuratan data dan angka yang disebutkan dalam artikel' }] },
      { _type: 'block', _key: 'ep-b7', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's12', text: 'Validitas kutipan dan sumber informasi' }] },
      { _type: 'block', _key: 'ep-b8', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's13', text: 'Konsistensi informasi dengan sumber terpercaya lainnya' }] },
      { _type: 'block', _key: 'ep-b9', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's14', text: 'Kesesuaian dengan peraturan perundang-undangan yang berlaku' }] },
      { _type: 'block', _key: 'ep-h2-3', style: 'h2', children: [{ _type: 'span', _key: 's15', text: 'Etika Jurnalistik' }] },
      { _type: 'block', _key: 'ep-p4', style: 'normal', children: [{ _type: 'span', _key: 's16', text: 'Warta Nusantara menerapkan prinsip-prinsip etika jurnalistik secara konsisten dalam setiap liputan.' }] },
      { _type: 'block', _key: 'ep-h3-1', style: 'h3', children: [{ _type: 'span', _key: 's17', text: 'Independensi' }] },
      { _type: 'block', _key: 'ep-p5', style: 'normal', children: [{ _type: 'span', _key: 's18', text: 'Berita ditulis tanpa pengaruh dari pihak manapun, baik politik, bisnis, maupun kepentingan lain yang dapat mengorbankan objektivitas liputan.' }] },
      { _type: 'block', _key: 'ep-h3-2', style: 'h3', children: [{ _type: 'span', _key: 's19', text: 'Objektivitas' }] },
      { _type: 'block', _key: 'ep-p6', style: 'normal', children: [{ _type: 'span', _key: 's20', text: 'Kami menyajikan fakta secara berimbang tanpa bias, memaparkan berbagai sudut pandang dari pihak-pihak yang terlibat.' }] },
      { _type: 'block', _key: 'ep-h3-3', style: 'h3', children: [{ _type: 'span', _key: 's21', text: 'Transparansi' }] },
      { _type: 'block', _key: 'ep-p7', style: 'normal', children: [{ _type: 'span', _key: 's22', text: 'Kami menyebutkan sumber informasi secara terbuka dan memberikan penjelasan jika sumber meminta anonimitas.' }] },
      { _type: 'block', _key: 'ep-h3-4', style: 'h3', children: [{ _type: 'span', _key: 's23', text: 'Akuntabilitas' }] },
      { _type: 'block', _key: 'ep-p8', style: 'normal', children: [{ _type: 'span', _key: 's24', text: 'Kami bersedia memperbaiki kesalahan jika ditemukan dan memberikan ruang bagi pihak yang merasa dirugikan untuk memberikan hak jawab.' }] },
      { _type: 'block', _key: 'ep-h2-4', style: 'h2', children: [{ _type: 'span', _key: 's25', text: 'Koreksi dan Hak Jawab' }] },
      { _type: 'block', _key: 'ep-p9', style: 'normal', children: [{ _type: 'span', _key: 's26', text: 'Jika ditemukan kesalahan dalam artikel kami, kami berkomitmen untuk:' }] },
      { _type: 'block', _key: 'ep-b10', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's27', text: 'Memperbaiki kesalahan secepat mungkin setelah dikonfirmasi' }] },
      { _type: 'block', _key: 'ep-b11', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's28', text: 'Memberikan koreksi yang jelas dan transparan di artikel yang bersangkutan' }] },
      { _type: 'block', _key: 'ep-b12', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's29', text: 'Memberikan hak jawab bagi pihak yang dirugikan tanpa dipotong atau diubah' }] },
      { _type: 'block', _key: 'ep-p10', style: 'normal', children: [{ _type: 'span', _key: 's30', text: 'Untuk koreksi atau hak jawab, hubungi: editor@tanahjarang.com' }] },
      { _type: 'block', _key: 'ep-h2-5', style: 'h2', children: [{ _type: 'span', _key: 's31', text: 'Penggunaan Konten' }] },
      { _type: 'block', _key: 'ep-p11', style: 'normal', children: [{ _type: 'span', _key: 's32', text: 'Pengunjung diperbolehkan membaca dan membagikan artikel dengan menyertakan tautan sumber asli dari Warta Nusantara. Penggunaan konten untuk keperluan komersial memerlukan izin tertulis dari redaksi.' }] },
    ],
  },
  {
    _type: 'page',
    _id: 'page-ai-disclaimer',
    title: 'Pernyataan Penggunaan AI',
    slug: { _type: 'slug', current: 'ai-disclaimer' },
    description: 'Pernyataan transparansi penggunaan kecerdasan buatan (AI) di Warta Nusantara.',
    body: [
      { _type: 'block', _key: 'ai1', style: 'normal', children: [{ _type: 'span', _key: 's1', text: 'Warta Nusantara berkomitmen untuk transparan dalam penggunaan teknologi kecerdasan buatan (AI). Halaman ini menjelaskan bagaimana kami menggunakan AI dalam operasional dan produksi konten.' }] },
      { _type: 'block', _key: 'ai-h2-1', style: 'h2', children: [{ _type: 'span', _key: 's2', text: 'Penggunaan Kecerdasan Buatan' }] },
      { _type: 'block', _key: 'ai-p2', style: 'normal', children: [{ _type: 'span', _key: 's3', text: 'Warta Nusantara menggunakan teknologi AI sebagai alat bantu dalam beberapa aspek operasional kami untuk meningkatkan kualitas dan efisiensi produksi konten.' }] },
      { _type: 'block', _key: 'ai-h3-1', style: 'h3', children: [{ _type: 'span', _key: 's4', text: 'Bantuan Penulisan' }] },
      { _type: 'block', _key: 'ai-p3', style: 'normal', children: [{ _type: 'span', _key: 's5', text: 'AI dapat digunakan sebagai alat bantu untuk merangkum informasi, mengecek fakta, atau menyusun draft awal artikel. Namun, setiap konten yang dihasilkan dengan bantuan AI tetap melewati proses review dan editing oleh tim editorial manusia sebelum dipublikasikan.' }] },
      { _type: 'block', _key: 'ai-h3-2', style: 'h3', children: [{ _type: 'span', _key: 's6', text: 'Analisis Data' }] },
      { _type: 'block', _key: 'ai-p4', style: 'normal', children: [{ _type: 'span', _key: 's7', text: 'AI dapat digunakan untuk menganalisis tren berita, data numerik, dan informasi pasar untuk membantu redaksi memahami konteks dan tren yang relevan.' }] },
      { _type: 'block', _key: 'ai-h3-3', style: 'h3', children: [{ _type: 'span', _key: 's8', text: 'Saran Konten' }] },
      { _type: 'block', _key: 'ai-p5', style: 'normal', children: [{ _type: 'span', _key: 's9', text: 'AI dapat membantu mengidentifikasi topik yang relevan untuk liputan berdasarkan tren pencarian dan minat pembaca.' }] },
      { _type: 'block', _key: 'ai-h2-2', style: 'h2', children: [{ _type: 'span', _key: 's10', text: 'Jaminan Kualitas' }] },
      { _type: 'block', _key: 'ai-p6', style: 'normal', children: [{ _type: 'span', _key: 's11', text: 'Kami menjamin bahwa penggunaan AI tidak mengorbankan kualitas dan akurasi konten yang dipublikasikan.' }] },
      { _type: 'block', _key: 'ai-b1', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's12', text: 'Semua konten yang dipublikasikan telah direview oleh editor manusia' }] },
      { _type: 'block', _key: 'ai-b2', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's13', text: 'Informasi diverifikasi dari sumber yang kredibel sebelum dipublikasikan' }] },
      { _type: 'block', _key: 'ai-b3', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's14', text: 'Kami tidak menggunakan AI untuk membuat konten yang menyesatkan atau hoaks' }] },
      { _type: 'block', _key: 'ai-b4', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's15', text: 'Setiap kesalahan akan diperbaiki dengan transparan' }] },
      { _type: 'block', _key: 'ai-h2-3', style: 'h2', children: [{ _type: 'span', _key: 's16', text: 'Transparansi' }] },
      { _type: 'block', _key: 'ai-p7', style: 'normal', children: [{ _type: 'span', _key: 's17', text: 'Jika sebuah artikel menggunakan bantuan AI secara signifikan dalam proses penulisannya, kami akan menyertakan catatan khusus di artikel tersebut untuk memberitahu pembaca.' }] },
      { _type: 'block', _key: 'ai-h2-4', style: 'h2', children: [{ _type: 'span', _key: 's18', text: 'Prinsip Penggunaan AI' }] },
      { _type: 'block', _key: 'ai-p8', style: 'normal', children: [{ _type: 'span', _key: 's19', text: 'Kami percaya bahwa teknologi harus digunakan untuk meningkatkan kualitas jurnalisme, bukan menggantikan peran jurnalis profesional. AI adalah alat bantu, bukan pengganti pertimbangan editorial manusia.' }] },
      { _type: 'block', _key: 'ai-h2-5', style: 'h2', children: [{ _type: 'span', _key: 's20', text: 'Hubungi Kami' }] },
      { _type: 'block', _key: 'ai-p9', style: 'normal', children: [{ _type: 'span', _key: 's21', text: 'Untuk pertanyaan lebih lanjut mengenai penggunaan AI di website kami, hubungi: editor@tanahjarang.com' }] },
    ],
  },
];

// Simplified pages for privacy, terms, contact, DMCA (shorter content)
const simplePages = [
  {
    _type: 'page',
    _id: 'page-kebijakan-privasi',
    title: 'Kebijakan Privasi',
    slug: { _type: 'slug', current: 'kebijakan-privasi' },
    description: 'Kebijakan privasi website Warta Nusantara — bagaimana kami mengumpulkan, menggunakan, dan melindungi data Anda.',
    body: [
      { _type: 'block', _key: 'kp1', style: 'normal', children: [{ _type: 'span', _key: 's1', text: 'Kebijakan privasi ini menjelaskan bagaimana Warta Nusantara mengumpulkan, menggunakan, dan melindungi informasi pribadi pengunjung website kami. Dengan mengakses website ini, Anda menyetujui praktik yang dijelaskan dalam kebijakan ini.' }] },
      { _type: 'block', _key: 'kp-h2-1', style: 'h2', children: [{ _type: 'span', _key: 's2', text: 'Informasi yang Kami Kumpulkan' }] },
      { _type: 'block', _key: 'kp-p2', style: 'normal', children: [{ _type: 'span', _key: 's3', text: 'Kami dapat mengumpulkan informasi berikut saat Anda mengunjungi website kami:' }] },
      { _type: 'block', _key: 'kp-h3-1', style: 'h3', children: [{ _type: 'span', _key: 's4', text: 'Data Penggunaan Website' }] },
      { _type: 'block', _key: 'kp-b1', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's5', text: 'Halaman yang dikunjungi dan durasi kunjungan' }] },
      { _type: 'block', _key: 'kp-b2', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's6', text: 'Sumber lalu lintas (dari mana Anda mengakses website kami)' }] },
      { _type: 'block', _key: 'kp-b3', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's7', text: 'Tindakan yang dilakukan di website (klik, scroll, pencarian)' }] },
      { _type: 'block', _key: 'kp-h3-2', style: 'h3', children: [{ _type: 'span', _key: 's8', text: 'Informasi Perangkat' }] },
      { _type: 'block', _key: 'kp-b4', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's9', text: 'Jenis browser dan versi' }] },
      { _type: 'block', _key: 'kp-b5', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's10', text: 'Sistem operasi yang digunakan' }] },
      { _type: 'block', _key: 'kp-b6', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's11', text: 'Resolusi layar dan jenis perangkat' }] },
      { _type: 'block', _key: 'kp-h3-3', style: 'h3', children: [{ _type: 'span', _key: 's12', text: 'Alamat IP' }] },
      { _type: 'block', _key: 'kp-p3', style: 'normal', children: [{ _type: 'span', _key: 's13', text: 'Alamat IP dikumpulkan untuk keamanan website dan analitik pengunjung. Alamat IP tidak dikaitkan dengan informasi pribadi lainnya.' }] },
      { _type: 'block', _key: 'kp-h2-2', style: 'h2', children: [{ _type: 'span', _key: 's14', text: 'Penggunaan Informasi' }] },
      { _type: 'block', _key: 'kp-p4', style: 'normal', children: [{ _type: 'span', _key: 's15', text: 'Informasi yang dikumpulkan digunakan untuk:' }] },
      { _type: 'block', _key: 'kp-b7', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's16', text: 'Meningkatkan kualitas layanan dan konten website' }] },
      { _type: 'block', _key: 'kp-b8', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's17', text: 'Analitik pengunjung untuk memahami preferensi pembaca' }] },
      { _type: 'block', _key: 'kp-b9', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's18', text: 'Keamanan website dari penyalahgunaan dan serangan siber' }] },
      { _type: 'block', _key: 'kp-b10', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's19', text: 'Menyajikan konten yang lebih relevan bagi pembaca' }] },
      { _type: 'block', _key: 'kp-h2-3', style: 'h2', children: [{ _type: 'span', _key: 's20', text: 'Cookie' }] },
      { _type: 'block', _key: 'kp-p5', style: 'normal', children: [{ _type: 'span', _key: 's21', text: 'Website kami menggunakan cookie untuk meningkatkan pengalaman pengguna. Cookie adalah file kecil yang disimpan di perangkat Anda oleh website.' }] },
      { _type: 'block', _key: 'kp-h3-4', style: 'h3', children: [{ _type: 'span', _key: 's22', text: 'Jenis Cookie yang Digunakan' }] },
      { _type: 'block', _key: 'kp-b11', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's23', text: 'Cookie Fungsional', marks: ['strong'] }, { _type: 'span', _key: 's24', text: ' — Diperlukan untuk fitur dasar website seperti pengaturan mode gelap' }] },
      { _type: 'block', _key: 'kp-b12', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's25', text: 'Cookie Analitik', marks: ['strong'] }, { _type: 'span', _key: 's26', text: ' — Membantu kami memahami bagaimana pengunjung menggunakan website' }] },
      { _type: 'block', _key: 'kp-b13', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's27', text: 'Cookie Iklan', marks: ['strong'] }, { _type: 'span', _key: 's28', text: ' — Digunakan oleh Google AdSense untuk menampilkan iklan yang relevan' }] },
      { _type: 'block', _key: 'kp-h3-5', style: 'h3', children: [{ _type: 'span', _key: 's29', text: 'Mengelola Cookie' }] },
      { _type: 'block', _key: 'kp-p6', style: 'normal', children: [{ _type: 'span', _key: 's30', text: 'Anda dapat mengatur browser Anda untuk menolak cookie atau memberitahu Anda saat cookie dikirimkan. Namun, beberapa fitur website mungkin tidak berfungsi dengan baik tanpa cookie.' }] },
      { _type: 'block', _key: 'kp-h2-4', style: 'h2', children: [{ _type: 'span', _key: 's31', text: 'Google AdSense' }] },
      { _type: 'block', _key: 'kp-p7', style: 'normal', children: [{ _type: 'span', _key: 's32', text: 'Website kami menggunakan Google AdSense untuk menampilkan iklan. Google menggunakan cookie untuk menampilkan iklan berdasarkan kunjungan sebelumnya ke website kami atau website lain di internet.' }] },
      { _type: 'block', _key: 'kp-h2-5', style: 'h2', children: [{ _type: 'span', _key: 's33', text: 'Tautan Eksternal' }] },
      { _type: 'block', _key: 'kp-p8', style: 'normal', children: [{ _type: 'span', _key: 's34', text: 'Website kami mungkin berisi tautan ke website pihak ketiga. Kami tidak bertanggung jawab atas konten atau kebijakan privasi website eksternal tersebut.' }] },
      { _type: 'block', _key: 'kp-h2-6', style: 'h2', children: [{ _type: 'span', _key: 's35', text: 'Keamanan Data' }] },
      { _type: 'block', _key: 'kp-p9', style: 'normal', children: [{ _type: 'span', _key: 's36', text: 'Kami menerapkan langkah-langkah keamanan yang wajar untuk melindungi informasi yang dikumpulkan dari akses, penggunaan, atau pengungkapan yang tidak sah.' }] },
      { _type: 'block', _key: 'kp-h2-7', style: 'h2', children: [{ _type: 'span', _key: 's37', text: 'Hak Anda' }] },
      { _type: 'block', _key: 'kp-p10', style: 'normal', children: [{ _type: 'span', _key: 's38', text: 'Anda memiliki hak untuk:' }] },
      { _type: 'block', _key: 'kp-b14', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's39', text: 'Mengetahui informasi apa yang kami kumpulkan tentang Anda' }] },
      { _type: 'block', _key: 'kp-b15', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's40', text: 'Meminta penghapusan data pribadi Anda' }] },
      { _type: 'block', _key: 'kp-b16', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's41', text: 'Menolak penggunaan data Anda untuk tujuan tertentu' }] },
      { _type: 'block', _key: 'kp-b17', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's42', text: 'Mengakses data pribadi yang kami miliki tentang Anda' }] },
      { _type: 'block', _key: 'kp-h2-8', style: 'h2', children: [{ _type: 'span', _key: 's43', text: 'Perubahan Kebijakan' }] },
      { _type: 'block', _key: 'kp-p11', style: 'normal', children: [{ _type: 'span', _key: 's44', text: 'Kami berhak memperbarui kebijakan privasi ini sewaktu-waktu. Perubahan akan dipublikasikan di halaman ini dengan tanggal pembaruan yang tercantum.' }] },
      { _type: 'block', _key: 'kp-h2-9', style: 'h2', children: [{ _type: 'span', _key: 's45', text: 'Hubungi Kami' }] },
      { _type: 'block', _key: 'kp-p12', style: 'normal', children: [{ _type: 'span', _key: 's46', text: 'Jika Anda memiliki pertanyaan tentang kebijakan privasi ini, silakan hubungi kami melalui email: info@tanahjarang.com' }] },
    ],
  },
  {
    _type: 'page',
    _id: 'page-syarat-dan-ketentuan',
    title: 'Syarat dan Ketentuan',
    slug: { _type: 'slug', current: 'syarat-dan-ketentuan' },
    description: 'Syarat dan ketentuan penggunaan website Warta Nusantara.',
    body: [
      { _type: 'block', _key: 'sk1', style: 'normal', children: [{ _type: 'span', _key: 's1', text: 'Syarat dan ketentuan ini berlaku untuk penggunaan website Warta Nusantara (tanahjarang.com). Dengan mengakses dan menggunakan website ini, Anda setuju untuk terikat dengan syarat dan ketentuan berikut.' }] },
      { _type: 'block', _key: 'sk-h2-1', style: 'h2', children: [{ _type: 'span', _key: 's2', text: 'Penerimaan Syarat' }] },
      { _type: 'block', _key: 'sk-p2', style: 'normal', children: [{ _type: 'span', _key: 's3', text: 'Dengan mengakses dan menggunakan website Warta Nusantara, Anda menyatakan telah membaca, memahami, dan menyetujui syarat dan ketentuan ini. Jika Anda tidak setuju dengan syarat dan ketentuan ini, Anda tidak diperkenankan menggunakan website ini.' }] },
      { _type: 'block', _key: 'sk-h2-2', style: 'h2', children: [{ _type: 'span', _key: 's4', text: 'Hak Cipta dan Kekayaan Intelektual' }] },
      { _type: 'block', _key: 'sk-p3', style: 'normal', children: [{ _type: 'span', _key: 's5', text: 'Seluruh konten yang dipublikasikan di website ini dilindungi oleh hak cipta dan undang-undang kekayaan intelektual yang berlaku.' }] },
      { _type: 'block', _key: 'sk-h2-3', style: 'h2', children: [{ _type: 'span', _key: 's6', text: 'Penggunaan Konten' }] },
      { _type: 'block', _key: 'sk-h3-1', style: 'h3', children: [{ _type: 'span', _key: 's7', text: 'Penggunaan yang Diizinkan' }] },
      { _type: 'block', _key: 'sk-p4', style: 'normal', children: [{ _type: 'span', _key: 's8', text: 'Anda diperbolehkan untuk:' }] },
      { _type: 'block', _key: 'sk-b1', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's9', text: 'Membaca dan mengakses artikel untuk keperluan pribadi' }] },
      { _type: 'block', _key: 'sk-b2', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's10', text: 'Membagikan artikel melalui tautan langsung (direct link) ke halaman asli' }] },
      { _type: 'block', _key: 'sk-b3', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's11', text: 'Mengutip potongan singkat dengan mencantumkan sumber dan tautan asli' }] },
      { _type: 'block', _key: 'sk-b4', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's12', text: 'Mencetak artikel untuk keperluan pribadi atau edukasi' }] },
      { _type: 'block', _key: 'sk-h3-2', style: 'h3', children: [{ _type: 'span', _key: 's13', text: 'Penggunaan yang Dilarang' }] },
      { _type: 'block', _key: 'sk-p5', style: 'normal', children: [{ _type: 'span', _key: 's14', text: 'Anda dilarang untuk:' }] },
      { _type: 'block', _key: 'sk-b5', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's15', text: 'Menyalin seluruh atau sebagian besar artikel dan mempublikasikannya kembali tanpa izin tertulis' }] },
      { _type: 'block', _key: 'sk-b6', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's16', text: 'Menggunakan konten untuk keperluan komersial tanpa lisensi' }] },
      { _type: 'block', _key: 'sk-b7', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's17', text: 'Mengubah, memodifikasi, atau membuat karya turunan dari konten tanpa izin' }] },
      { _type: 'block', _key: 'sk-b8', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's18', text: 'Mendistribusikan ulang konten melalui platform lain tanpa atribusi yang memadai' }] },
      { _type: 'block', _key: 'sk-h2-4', style: 'h2', children: [{ _type: 'span', _key: 's19', text: 'Tautan Eksternal' }] },
      { _type: 'block', _key: 'sk-p6', style: 'normal', children: [{ _type: 'span', _key: 's20', text: 'Website ini mungkin berisi tautan ke website pihak ketiga. Warta Nusantara tidak bertanggung jawab atas konten, kebijakan privasi, atau praktik website eksternal tersebut.' }] },
      { _type: 'block', _key: 'sk-h2-5', style: 'h2', children: [{ _type: 'span', _key: 's21', text: 'Batasan Tanggung Jawab' }] },
      { _type: 'block', _key: 'sk-p7', style: 'normal', children: [{ _type: 'span', _key: 's22', text: 'Informasi yang dipublikasikan di Warta Nusantara disediakan untuk tujuan informasi umum. Kami berusaha memastikan akurasi informasi, namun tidak memberikan jaminan atas kelengkapan, keandalan, atau akurasi informasi tersebut.' }] },
      { _type: 'block', _key: 'sk-h2-6', style: 'h2', children: [{ _type: 'span', _key: 's23', text: 'Perubahan Syarat' }] },
      { _type: 'block', _key: 'sk-p8', style: 'normal', children: [{ _type: 'span', _key: 's24', text: 'Kami berhak mengubah syarat dan ketentuan ini sewaktu-waktu tanpa pemberitahuan sebelumnya.' }] },
      { _type: 'block', _key: 'sk-h2-7', style: 'h2', children: [{ _type: 'span', _key: 's25', text: 'Hukum yang Berlaku' }] },
      { _type: 'block', _key: 'sk-p9', style: 'normal', children: [{ _type: 'span', _key: 's26', text: 'Syarat dan ketentuan ini tunduk pada hukum Negara Kesatuan Republik Indonesia.' }] },
      { _type: 'block', _key: 'sk-h2-8', style: 'h2', children: [{ _type: 'span', _key: 's27', text: 'Hubungi Kami' }] },
      { _type: 'block', _key: 'sk-p10', style: 'normal', children: [{ _type: 'span', _key: 's28', text: 'Jika Anda memiliki pertanyaan tentang syarat dan ketentuan ini, silakan hubungi kami melalui email: info@tanahjarang.com' }] },
    ],
  },
  {
    _type: 'page',
    _id: 'page-hubungi-kami',
    title: 'Hubungi Kami',
    slug: { _type: 'slug', current: 'hubungi-kami' },
    description: 'Hubungi tim Warta Nusantara untuk pertanyaan, saran, koreksi berita, atau kerja sama.',
    body: [
      { _type: 'block', _key: 'hk1', style: 'normal', children: [{ _type: 'span', _key: 's1', text: 'Kami senang mendengar dari Anda! Jika Anda memiliki pertanyaan, saran, koreksi berita, atau ingin menjalin kerja sama, jangan ragu untuk menghubungi kami.' }] },
      { _type: 'block', _key: 'hk-h2-1', style: 'h2', children: [{ _type: 'span', _key: 's2', text: 'Informasi Kontak' }] },
      { _type: 'block', _key: 'hk-p2', style: 'normal', children: [{ _type: 'span', _key: 's3', text: 'Anda dapat menghubungi kami melalui email: info@tanahjarang.com' }] },
      { _type: 'block', _key: 'hk-h2-2', style: 'h2', children: [{ _type: 'span', _key: 's4', text: 'Sosial Media' }] },
      { _type: 'block', _key: 'hk-p3', style: 'normal', children: [{ _type: 'span', _key: 's5', text: 'Ikuti kami di media sosial untuk mendapatkan berita terkini dan informasi terbaru dari Warta Nusantara:' }] },
      { _type: 'block', _key: 'hk-b1', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's6', text: 'WhatsApp — Kirim pesan langsung kepada kami' }] },
      { _type: 'block', _key: 'hk-b2', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's7', text: 'Google News — Ikuti Warta Nusantara untuk pembaruan berita' }] },
      { _type: 'block', _key: 'hk-h2-3', style: 'h2', children: [{ _type: 'span', _key: 's8', text: 'Untuk Liputan dan Kerja Sama' }] },
      { _type: 'block', _key: 'hk-h3-1', style: 'h3', children: [{ _type: 'span', _key: 's9', text: 'Kerja Sama Bisnis dan Periklanan' }] },
      { _type: 'block', _key: 'hk-p4', style: 'normal', children: [{ _type: 'span', _key: 's10', text: 'Untuk keperluan kerja sama bisnis, periklanan, atau sponsorship, silakan email kami dengan subjek "Kerja Sama Bisnis" agar dapat kami proses lebih cepat.' }] },
      { _type: 'block', _key: 'hk-h3-2', style: 'h3', children: [{ _type: 'span', _key: 's11', text: 'Press Release dan Liputan' }] },
      { _type: 'block', _key: 'hk-p5', style: 'normal', children: [{ _type: 'span', _key: 's12', text: 'Untuk pengiriman press release atau permintaan liputan, silakan hubungi kami melalui email dengan subjek "Press Release" atau "Permintaan Liputan".' }] },
      { _type: 'block', _key: 'hk-h3-3', style: 'h3', children: [{ _type: 'span', _key: 's13', text: 'Koreksi Berita' }] },
      { _type: 'block', _key: 'hk-p6', style: 'normal', children: [{ _type: 'span', _key: 's14', text: 'Jika Anda menemukan kesalahan informasi dalam artikel kami, silakan hubungi tim redaksi melalui email: editor@tanahjarang.com' }] },
      { _type: 'block', _key: 'hk-h2-4', style: 'h2', children: [{ _type: 'span', _key: 's15', text: 'Hak Jawab' }] },
      { _type: 'block', _key: 'hk-p7', style: 'normal', children: [{ _type: 'span', _key: 's16', text: 'Jika Anda merasa informasi dalam artikel kami merugikan Anda atau pihak yang Anda wakili, Anda berhak memberikan hak jawab. Silakan hubungi kami melalui email di atas dengan subjek "Hak Jawab".' }] },
    ],
  },
  {
    _type: 'page',
    _id: 'page-dmca',
    title: 'Kebijakan DMCA',
    slug: { _type: 'slug', current: 'dmca' },
    description: 'Kebijakan DMCA Warta Nusantara — prosedur pelaporan pelanggaran hak cipta dan perlindungan konten.',
    body: [
      { _type: 'block', _key: 'dm1', style: 'normal', children: [{ _type: 'span', _key: 's1', text: 'Warta Nusantara (tanahjarang.com) berkomitmen penuh untuk menghormati hak cipta dan kekayaan intelektual pihak lain. Kami menerapkan kebijakan yang ketat terkait pelanggaran hak cipta dan akan merespons pemberitahuan yang sah sesuai dengan Undang-Undang Hak Cipta Digital Milenium (DMCA) tahun 1998.' }] },
      { _type: 'block', _key: 'dm-h2-1', style: 'h2', children: [{ _type: 'span', _key: 's2', text: 'Pernyataan Komitmen' }] },
      { _type: 'block', _key: 'dm-p2', style: 'normal', children: [{ _type: 'span', _key: 's3', text: 'Semua konten yang dipublikasikan di Warta Nusantara harus mematuhi hukum hak cipta yang berlaku. Jika Anda adalah pemilik hak cipta dan yakin bahwa materi di situs kami melanggar hak cipta Anda, silakan beritahu kami sesuai prosedur yang dijelaskan di bawah ini.' }] },
      { _type: 'block', _key: 'dm-h2-2', style: 'h2', children: [{ _type: 'span', _key: 's4', text: 'Definisi Hak Cipta' }] },
      { _type: 'block', _key: 'dm-p3', style: 'normal', children: [{ _type: 'span', _key: 's5', text: 'Hak cipta adalah hak eksklusif yang diberikan oleh undang-undang kepada pencipta karya asli untuk mengontrol penggunaan, distribusi, dan reproduksi karya tersebut. Ini mencakup:' }] },
      { _type: 'block', _key: 'dm-b1', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's6', text: 'Teks tulisan, artikel, dan karya literatur lainnya' }] },
      { _type: 'block', _key: 'dm-b2', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's7', text: 'Foto, gambar, dan karya visual lainnya' }] },
      { _type: 'block', _key: 'dm-b3', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's8', text: 'Video, audio, dan musik' }] },
      { _type: 'block', _key: 'dm-b4', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's9', text: 'Perangkat lunak dan kode program' }] },
      { _type: 'block', _key: 'dm-b5', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's10', text: 'Karya seni dan desain grafis' }] },
      { _type: 'block', _key: 'dm-h2-3', style: 'h2', children: [{ _type: 'span', _key: 's11', text: 'Kebijakan Penggunaan Konten' }] },
      { _type: 'block', _key: 'dm-h3-1', style: 'h3', children: [{ _type: 'span', _key: 's12', text: 'Penggunaan yang Diizinkan' }] },
      { _type: 'block', _key: 'dm-p4', style: 'normal', children: [{ _type: 'span', _key: 's13', text: 'Pengunjung diperbolehkan untuk:' }] },
      { _type: 'block', _key: 'dm-b6', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's14', text: 'Membaca dan mengakses artikel untuk keperluan pribadi' }] },
      { _type: 'block', _key: 'dm-b7', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's15', text: 'Membagikan artikel melalui tautan langsung ke halaman asli' }] },
      { _type: 'block', _key: 'dm-b8', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's16', text: 'Mengutip potongan singkat (fair use) dengan mencantumkan sumber' }] },
      { _type: 'block', _key: 'dm-b9', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's17', text: 'Mencetak artikel untuk keperluan pribadi atau edukasi' }] },
      { _type: 'block', _key: 'dm-h3-2', style: 'h3', children: [{ _type: 'span', _key: 's18', text: 'Penggunaan yang Dilarang' }] },
      { _type: 'block', _key: 'dm-p5', style: 'normal', children: [{ _type: 'span', _key: 's19', text: 'Pengunjung dilarang untuk:' }] },
      { _type: 'block', _key: 'dm-b10', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's20', text: 'Menyalin seluruh atau sebagian besar artikel tanpa izin tertulis' }] },
      { _type: 'block', _key: 'dm-b11', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's21', text: 'Menggunakan konten untuk keperluan komersial tanpa lisensi' }] },
      { _type: 'block', _key: 'dm-b12', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's22', text: 'Mengubah atau membuat karya turunan dari konten tanpa izin' }] },
      { _type: 'block', _key: 'dm-b13', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's23', text: 'Mendistribusikan ulang konten tanpa atribusi yang memadai' }] },
      { _type: 'block', _key: 'dm-b14', style: 'normal', list: 'bullet', children: [{ _type: 'span', _key: 's24', text: 'Menggunakan foto atau gambar untuk keperluan komersial tanpa izin' }] },
      { _type: 'block', _key: 'dm-h2-4', style: 'h2', children: [{ _type: 'span', _key: 's25', text: 'Prosedur Pelaporan DMCA' }] },
      { _type: 'block', _key: 'dm-p6', style: 'normal', children: [{ _type: 'span', _key: 's26', text: 'Jika Anda yakin bahwa materi di Warta Nusantara melanggar hak cipta Anda, silakan kirimkan pemberitahuan yang sah kepada DMCA Agent kami.' }] },
      { _type: 'block', _key: 'dm-h3-3', style: 'h3', children: [{ _type: 'span', _key: 's27', text: 'Isi Pemberitahuan DMCA' }] },
      { _type: 'block', _key: 'dm-p7', style: 'normal', children: [{ _type: 'span', _key: 's28', text: 'Pemberitahuan harus memuat informasi berikut:' }] },
      { _type: 'block', _key: 'dm-o1', style: 'normal', list: 'number', level: 1, children: [{ _type: 'span', _key: 's29', text: 'Tanda tangan elektronik atau fisik', marks: ['strong'] }, { _type: 'span', _key: 's30', text: ' dari pemilik hak cipta atau orang yang berwenang' }] },
      { _type: 'block', _key: 'dm-o2', style: 'normal', list: 'number', level: 1, children: [{ _type: 'span', _key: 's31', text: 'Identifikasi karya berhak cipta', marks: ['strong'] }, { _type: 'span', _key: 's32', text: ' yang diklaim telah dilanggar' }] },
      { _type: 'block', _key: 'dm-o3', style: 'normal', list: 'number', level: 1, children: [{ _type: 'span', _key: 's33', text: 'Identifikasi materi yang melanggar', marks: ['strong'] }, { _type: 'span', _key: 's34', text: ' dan lokasi (URL) di situs kami' }] },
      { _type: 'block', _key: 'dm-o4', style: 'normal', list: 'number', level: 1, children: [{ _type: 'span', _key: 's35', text: 'Informasi kontak Anda', marks: ['strong'] }, { _type: 'span', _key: 's36', text: ', termasuk alamat, nomor telepon, dan email' }] },
      { _type: 'block', _key: 'dm-o5', style: 'normal', list: 'number', level: 1, children: [{ _type: 'span', _key: 's37', text: 'Pernyataan', marks: ['strong'] }, { _type: 'span', _key: 's38', text: ' bahwa Anda menggunakan niat baik' }] },
      { _type: 'block', _key: 'dm-o6', style: 'normal', list: 'number', level: 1, children: [{ _type: 'span', _key: 's39', text: 'Pernyataan', marks: ['strong'] }, { _type: 'span', _key: 's40', text: ' bahwa informasi dalam pemberitahuan akurat' }] },
      { _type: 'block', _key: 'dm-o7', style: 'normal', list: 'number', level: 1, children: [{ _type: 'span', _key: 's41', text: 'Tanda tangan', marks: ['strong'] }, { _type: 'span', _key: 's42', text: ' fisik atau elektronik' }] },
      { _type: 'block', _key: 'dm-h2-5', style: 'h2', children: [{ _type: 'span', _key: 's43', text: 'Informasi Kontak DMCA Agent' }] },
      { _type: 'block', _key: 'dm-p8', style: 'normal', children: [{ _type: 'span', _key: 's44', text: 'Untuk melaporkan pelanggaran DMCA, silakan hubungi: DMCA Agent, Warta Nusantara, Email: dmca@tanahjarang.com, Email Alternatif: redaksi@tanahjarang.com' }] },
      { _type: 'block', _key: 'dm-p9', style: 'normal', children: [{ _type: 'span', _key: 's45', text: 'Harap sertakan kata "DMCA Notice" pada baris subjek email agar laporan Anda dapat segera ditangani.' }] },
      { _type: 'block', _key: 'dm-h2-6', style: 'h2', children: [{ _type: 'span', _key: 's46', text: 'Proses Peninjauan' }] },
      { _type: 'block', _key: 'dm-p10', style: 'normal', children: [{ _type: 'span', _key: 's47', text: 'Setelah menerima pemberitahuan DMCA yang sah, kami akan:' }] },
      { _type: 'block', _key: 'dm-o8', style: 'normal', list: 'number', level: 1, children: [{ _type: 'span', _key: 's48', text: 'Meninjau pemberitahuan dan memverifikasi kelengkapan informasi' }] },
      { _type: 'block', _key: 'dm-o9', style: 'normal', list: 'number', level: 1, children: [{ _type: 'span', _key: 's49', text: 'Mengidentifikasi materi yang dilaporkan di situs kami' }] },
      { _type: 'block', _key: 'dm-o10', style: 'normal', list: 'number', level: 1, children: [{ _type: 'span', _key: 's50', text: 'Menghapus atau memblokir akses ke materi yang dilaporkan' }] },
      { _type: 'block', _key: 'dm-o11', style: 'normal', list: 'number', level: 1, children: [{ _type: 'span', _key: 's51', text: 'Memberitahu pengguna yang mempublikasikan materi tersebut' }] },
      { _type: 'block', _key: 'dm-o12', style: 'normal', list: 'number', level: 1, children: [{ _type: 'span', _key: 's52', text: 'Mencatat pemberitahuan dan tindakan yang diambil' }] },
      { _type: 'block', _key: 'dm-p11', style: 'normal', children: [{ _type: 'span', _key: 's53', text: 'Kami berusaha merespons setiap pemberitahuan DMCA dalam waktu 48 jam kerja.' }] },
      { _type: 'block', _key: 'dm-h2-7', style: 'h2', children: [{ _type: 'span', _key: 's54', text: 'Prosedur Counter-Notice' }] },
      { _type: 'block', _key: 'dm-p12', style: 'normal', children: [{ _type: 'span', _key: 's55', text: 'Jika Anda yakin bahwa materi yang dihapus tidak melanggar hak cipta, Anda dapat mengirimkan Counter-Notice kepada DMCA Agent kami.' }] },
      { _type: 'block', _key: 'dm-h2-8', style: 'h2', children: [{ _type: 'span', _key: 's56', text: 'Pengulangan Pelanggaran' }] },
      { _type: 'block', _key: 'dm-p13', style: 'normal', children: [{ _type: 'span', _key: 's57', text: 'Warta Nusantara akan membatasi akses pengguna yang secara berulang melanggar hak cipta.' }] },
      { _type: 'block', _key: 'dm-h2-9', style: 'h2', children: [{ _type: 'span', _key: 's58', text: 'Modifikasi Kebijakan' }] },
      { _type: 'block', _key: 'dm-p14', style: 'normal', children: [{ _type: 'span', _key: 's59', text: 'Warta Nusantara berhak memodifikasi kebijakan DMCA ini sewaktu-waktu tanpa pemberitahuan sebelumnya.' }] },
    ],
  },
];

const allPages = [...pages, ...simplePages];

async function seed() {
  console.log('Seeding pages to Sanity...');
  for (const page of allPages) {
    try {
      await client.createOrReplace(page);
      console.log(`✓ Created: ${page.title} (${page.slug.current})`);
    } catch (err) {
      console.error(`✗ Failed: ${page.title}`, err.message);
    }
  }
  console.log('Done!');
}

seed();
